# Neural traces experiment configuration for all-rgc3 dataset
defaults:
  - neural_traces
  - _self_

dataset_name: "all-rgc3"
use_8hz_chirp: true  # Use the recommended 8Hz chirp
chirp_len: 259       # Updated chirp length based on our findings
bar_len: 32
feature_len: 3
train_split: 0.8
random_seed: 42
