# Optimal 20 Newsgroups dataset configuration for LDA
defaults:
  - newsgroups
  - _self_

# Standard content filtering (same for all models)  
remove: ["headers", "footers", "quotes"]

# Count vectorization (required for proper LDA)
use_count_vectorizer: true

# Feature selection optimized for LDA topic modeling
max_features: 10000      # Optimal for LDA - tested 8k/10k/12k/15k
min_df: 2               # Optimal - tested 2 vs 3 (+5.7% accuracy to 38.5%)
max_df: 0.9             # More aggressive common word removal for cleaner topics
