defaults:
  - config_schema
  - _self_

run_name: ${now:%Y%m%d-%H%M%S}
device: gpu
jit: true
use_local: true
use_wandb: true
repeat: 1
log_level: INFO
project: "goal"
group: null
job_type: null
from_epoch: null
sweep_id: null
run_id: null
from_scratch: false
