# Neural traces experiment configuration
defaults:
  - hmog_cyc
  - _self_

num_cycles: 40

pre:
  batch_size: 64
  min_var: 1e-5
  n_epochs: 10000
  lr_init: 1e-5
  lr_final_ratio: 0.1
  grad_clip: 0

lgm:
  batch_size: 64
  re_reg: 0.1
  n_epochs: 250
  min_var: 1e-5
  lr_init: 1e-6
  grad_clip: 0

mix:
  batch_size: 64
  n_epochs: 250
  lr_init: 1e-6
  grad_clip: 0

full:
  n_epochs: 0
