# Final optimized PCA+K-means model for 20 Newsgroups
defaults:
  - pca_kmeans
  - _self_

n_clusters: 20

# Optimal PCA parameters (confirmed from testing)
n_components: 150        # Optimal - tested 80, 100, 120, 130, 200
pca_random_state: 42

# Maximally optimized K-means parameters
random_state: 42
max_iter: 500           # More iterations for perfect convergence
n_init: 30             # Many more random restarts 
tol: 1e-6              # Very tight convergence
algorithm: lloyd