# LDA benchmark for 20 Newsgroups dataset
defaults:
  - lda
  - _self_

# Match newsgroups categories
n_clusters: 20           # 20 newsgroups categories
random_state: 42

# Optimized for speed on high-dimensional text
max_iter: 50             # Reduced for faster execution
learning_method: online  # Faster for large sparse datasets
alpha: 0.1              # Moderate topic mixing per document  
beta: 0.01              # Sparse topics (fewer words per topic)
perp_tol: 1e-1          # Relaxed tolerance for faster convergence