# Final optimized PCA+K-means model for 20 Newsgroups
defaults:
  - pca_kmeans
  - _self_

n_clusters: 20

# Optimal PCA parameters (confirmed from testing)
n_components: 150        # Optimal - tested 80, 100, 120, 130, 200
pca_random_state: 42

# Optimized K-means parameters (performance + efficiency)
random_state: 42
max_iter: 200           # Sufficient for convergence
n_init: 10             # Sufficient random restarts (tested vs 30)
tol: 1e-4              # Practical convergence tolerance  
algorithm: lloyd