# Optimal LDA configuration for 20 Newsgroups dataset
defaults:
  - lda
  - _self_

# Match newsgroups categories
n_clusters: 20           # 20 newsgroups categories
random_state: 42

# Optimized parameters achieving 38.5% accuracy
max_iter: 50             # Reduced for faster execution
learning_method: batch   # Optimal learning method
alpha: 1.0              # Optimal - high topic mixing per document  
beta: 0.1               # Optimal - moderate sparsity for topics
learning_decay: 0.7      # Standard decay rate
perp_tol: 0.1           # Relaxed tolerance for faster convergence