defaults:
  - hmog_diff
  - _self_

latent_dim: 40
n_clusters: 40

lr_scale_init: 1
lr_scale_final: 1
num_cycles: 10

lgm_noise_scale: 0.01
mix_noise_scale: 0.1

pre:
  lr: 3e-5
  n_epochs: 10000
  batch_steps: 1000
  l1_reg: 1e-3
  l2_reg: 0
  grad_clip: 1
  min_var: 1e-5
  jitter_var: 0

lgm:
  n_epochs: 0

mix:
  lr: 1e-5
  n_epochs: 1000
  batch_steps: 2000
  grad_clip: 1
  min_prob: 1e-4
  lat_min_var: 1e-6
  upr_prs_reg: 1e-3
  lwr_prs_reg: 1e-3
  l1_reg: ${model.pre.l1_reg}
  l2_reg: ${model.pre.l2_reg}

full:
  lr: 1e-5
  n_epochs: 1000
  batch_steps: 1000
  grad_clip: 1
  min_prob: ${model.mix.min_prob}
  obs_min_var: ${model.pre.min_var}
  lat_min_var: ${model.mix.lat_min_var}
  upr_prs_reg: ${model.mix.upr_prs_reg}
  lwr_prs_reg: ${model.mix.lwr_prs_reg}
  l1_reg: ${model.pre.l1_reg}
  l2_reg: ${model.pre.l2_reg}
