# Neural traces experiment configuration
defaults:
  - hmog_diff
  - _self_

latent_dim: 40
n_clusters: 40

lr_scale_init: 1
lr_scale_final: 1
num_cycles: 10

pre:
  lr: 3e-5
  n_epochs: 10000
  batch_steps: 1000
  l1_reg: 0
  l2_reg: 0
  grad_clip: 1
  min_var: 1e-5
  jitter_var: 0


lgm:
  n_epochs: 0

mix:
  n_epochs: 0

full:
  lr: 3e-5
  n_epochs: 10000
  batch_steps: 1000
  grad_clip: 1
  min_prob: 1e-4
  obs_min_var: 1e-5
  lat_min_var: 1e-6
  upr_prs_reg: 1e-3
  lwr_prs_reg: 1e-3
  l1_reg: 0
  l2_reg: 0

