# Tasic single-cell RNA-seq configuration for HMOG
defaults:
  - hmog_diff
  - _self_

# Model architecture - following successful MNIST/newsgroups patterns
latent_dim: 50       # Match MNIST's successful latent_dim
n_clusters: 133      # Target the actual 133 cell types from 2018 paper

# Training schedule - blend of MNIST efficiency and newsgroups conservatism
lr_scales: [1, 0.3, 0.1]  # Match newsgroups pattern
num_cycles: 5             # Match MNIST efficiency
lgm_noise_scale: 0.01     # Match successful configs
mix_noise_scale: 0.01

# Skip pre-training like successful configs
pre:
  n_epochs: 0

lgm:
  n_epochs: 0

mix:
  n_epochs: 0

# Full training - blend MNIST speed with newsgroups stability  
full:
  lr: 2e-4           # Between MNIST (3e-4) and newsgroups (1e-4)
  n_epochs: 300      # More than MNIST (100), less than old tasic (1000)
  batch_steps: 1000  # Match MNIST's successful batch size
  grad_clip: 1
  min_prob: 1e-5     # Match MNIST precision
  obs_min_var: 1e-6  # Match MNIST for log-transformed data
  lat_min_var: 1e-6
  upr_prs_reg: 1e-4  # Match MNIST's working regularization
  lwr_prs_reg: 1e-4
  l1_reg: 1e-3       # Match MNIST's gene selection strength
  l2_reg: 1e-4       # Consistent across successful configs
